import Link from "next/link";
import {notFound} from "next/navigation";
import {antagonistStatus,characterDisplayArt,characterResearch,characterResearchPaths,characterWorks,characters,classifyThreatVisual,getCharacter,slugify} from "@/lib/data";
import type {CSSProperties} from "react";
import {CharacterConnections} from "@/components/EntityConnections";
import {FitTitle} from "@/components/FitTitle";
export function generateStaticParams(){return characters.map(character=>({slug:slugify(character.name)}))}
const labels:Record<string,string>={identity:"Identity",gender:"Gender",lifeStatus:"Life status",communityCategories:"Community categories",narrativeRole:"Narrative role",subjects:"Subjects"};

export default async function Character({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params,character=getCharacter(slug);if(!character)notFound();
  const research=characterResearch(character.id),paths=characterResearchPaths(character.id),description=research?.claims.find(claim=>claim.predicate==="description"),intro=description?{text:String(description.value),provider:description.provider,url:description.url,status:description.verification,license:description.license,attribution:description.attribution,changes:description.changes}:paths?.intro,claims=research?.claims.filter(claim=>claim.predicate!=="description"&&claim.predicate!=="appearsIn")||[],works=characterWorks(character.id),secondary=research?.editorialStatus==="secondary-verified",record=String(characters.findIndex(item=>item.id===character.id)+1).padStart(3,"0"),initials=character.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("");
  const isAntagonist=antagonistStatus.characters[character.id]?.isAntagonist,artVariant=characters.findIndex(item=>item.id===character.id)%4;
  const visualClass=isAntagonist?classifyThreatVisual([character.name,character.characterType,typeof description?.value==="string"?description.value:paths?.intro?.text].filter(Boolean).join(" ")):undefined;
  const art=characterDisplayArt(character.name,Boolean(isAntagonist),visualClass),artStyle={"--entity-art":`url('${art.url}')`} as CSSProperties;
  return <main className={`identity-page entity-art display-art ${art.individual?"individual-art":"placeholder-art"} ${isAntagonist?"antagonist-art":"character-art"} art-variant-${artVariant}`} style={artStyle}>
    <section className="identity-hero"><Link href="/characters" className="identity-back">← RETURN TO THE POPULATION</Link><div className="identity-register"><span>IDENTITY FILE</span><b>{record} / {characters.length}</b></div><div className="identity-monogram" aria-hidden="true">{initials}</div><div className={`identity-heading name-${character.name.length<=14?"short":character.name.length<=25?"medium":"long"}`}><small>{secondary?"SECONDARY VERIFIED":"PROVISIONAL"} / CLAIM-LEVEL RECORD</small><FitTitle title={character.name}/><p>{works.length} known literary connection{works.length===1?"":"s"}</p></div><div className={`identity-stamp ${secondary?"secondary":"provisional"}`}>{secondary?"SOURCE\nMATCHED":"REVIEW\nREQUIRED"}</div><div className="identity-art-note">{art.credit.toUpperCase()} / NOT CANONICAL EVIDENCE</div><div className="identity-rule"><span>THE POPULATION / WHO WALKS BETWEEN THE PAGES</span><span>RECORD {record}</span></div></section>
    <section className="identity-body"><div className="identity-abstract">{intro?<><span>{intro.status.replaceAll("-"," ").toUpperCase()} ABSTRACT</span><p>{intro.text}</p><a href={intro.url} target="_blank" rel="noreferrer">{intro.provider}{intro.license?` · ${intro.license}`:""}{description?.revisionId?` · revision ${description.revisionId}`:""} ↗</a>{intro.attribution&&<small>{intro.attribution} {intro.changes}</small>}</>:<><span>DESCRIPTION WITHHELD</span><p>No directly matched, citable character description has been found. An unsourced biography has not been generated.</p></>} </div><aside><b>{works.length.toString().padStart(2,"0")}</b><span>CONNECTED<br/>WORKS</span><p>Absence of description is treated as an evidence gap, not permission to invent.</p></aside></section>
    <section className="identity-ledger"><header><span>EVIDENCE LEDGER</span><h2>WHAT CAN<br/><i>BE SAID?</i></h2><b>{claims.length.toString().padStart(2,"0")}</b></header><div>{claims.map((claim,index)=><article className="identity-claim" key={`${claim.predicate}-${index}`}><small>{String(index+1).padStart(2,"0")}</small><div><span>{labels[claim.predicate]||claim.predicate}{claim.spoiler&&" · SPOILER"}</span><p>{Array.isArray(claim.value)?claim.value.join(" · "):claim.value}</p></div><aside><span className={`status ${claim.verification==="secondary-verified"?"secondary":"provisional"}`}>{claim.verification.replace("-"," ")}</span><a href={claim.url} target="_blank" rel="noreferrer">{claim.provider} ↗</a></aside></article>)}</div><div className="identity-gap"><b>PRIMARY VERIFICATION NEEDED</b><p>A named edition, ISBN and page or chapter locator are required before this record can reach Primary verified status.</p></div></section>
    {paths&&<section className="identity-ledger research-paths"><header><span>RESEARCH PATHS</span><h2>READ<br/><i>FURTHER.</i></h2><b>{paths.researchSources.length.toString().padStart(2,"0")}</b></header><div>{paths.researchSources.map((source,index)=><article className="identity-claim" key={`${source.provider}-${source.url}`}><small>{String(index+1).padStart(2,"0")}</small><div><span>{source.sourceClass.replaceAll("-"," ")}</span><p>{source.sourceTitle}</p><small>{source.note}</small></div><aside><span className={`status ${source.verification==="official-index"||source.verification==="secondary-verified"?"secondary":"provisional"}`}>{source.verification.replaceAll("-"," ")}</span><a href={source.url} target="_blank" rel="noreferrer">{source.provider} ↗</a>{source.license&&<small>{source.license}</small>}</aside></article>)}</div><div className="identity-gap"><b>STARTING POINT, NOT A CONCLUSION</b><p>The abstract introduces the record. These links expose the evidence, community documentation and unresolved paths from which research can continue.</p></div></section>}
    <CharacterConnections characterId={character.id}/>
  </main>;
}
