import { works } from "@/lib/data";
export type PlaceKind = "fictional" | "real" | "screen"; export type MapStatus = "exact" | "approximate" | "inspired" | "unmapped";
export type Place = { id: string; name: string; kind: PlaceKind; region: string; mapStatus: MapStatus; x?: number; y?: number; summary: string; workTitles: string[]; inspiration?: string; source: { name: string; url: string; note: string } };
const wiki = (page: string, note = "Secondary reference; map placement is explicitly editorial.") => ({ name: "Wikipedia", url: `https://en.wikipedia.org/wiki/${page}`, note });
export const places: Place[] = [
    { id: "derry", name: "Derry", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 270, y: 425, summary: "A recurring fictional Maine city and the principal setting of It and Insomnia.", workTitles: ["It", "Insomnia", "Dreamcatcher", "11/22/63", "The Bird and the Album"], inspiration: "Bangor, Maine", source: wiki("Derry_(Stephen_King)", "Secondary reference; approximate map placement, not a canonical coordinate.") },
    { id: "castle-rock", name: "Castle Rock", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 105, y: 565, summary: "King's recurring small town in fictional Castle County, central to several Castle Rock stories.", workTitles: ["The Dead Zone", "Cujo", "The Dark Half", "Needful Things", "The Body", "The Sun Dog", "Elevation", "Gwendy's Button Box"], inspiration: "A composite of central and western Maine influences", source: wiki("Castle_Rock_(Stephen_King)") },
    { id: "jerusalems-lot", name: "Jerusalem's Lot", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 190, y: 455, summary: "The fictional Maine town also known as 'Salem's Lot.", workTitles: ["Salem's Lot", "Jerusalem's Lot", "One for the Road"], source: wiki("Jerusalem%27s_Lot") },
    { id: "chamberlain", name: "Chamberlain", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 215, y: 525, summary: "The fictional Maine town in which Carrie White grows up and attends school.", workTitles: ["Carrie"], source: wiki("Carrie_(novel)") },
    { id: "ludlow", name: "Ludlow", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 260, y: 395, summary: "The fictional Ludlow used in Pet Sematary, kept distinct from the real Maine community of the same name.", workTitles: ["Pet Sematary", "The Dark Half"], source: wiki("Pet_Sematary") },
    { id: "haven", name: "Haven", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 225, y: 445, summary: "The small fictional Maine town transformed by the buried object in The Tommyknockers.", workTitles: ["The Tommyknockers"], source: wiki("The_Tommyknockers") },
    { id: "chesters-mill", name: "Chester's Mill", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 125, y: 540, summary: "The fictional Maine town isolated beneath the transparent barrier in Under the Dome.", workTitles: ["Under the Dome"], source: wiki("Under_the_Dome_(novel)") },
    { id: "little-tall-island", name: "Little Tall Island", kind: "fictional", region: "Maine coast", mapStatus: "approximate", x: 410, y: 500, summary: "A fictional island community off the Maine coast, shared by Dolores Claiborne and Storm of the Century.", workTitles: ["Dolores Claiborne"], source: wiki("Dolores_Claiborne") },
    { id: "tarkers-mills", name: "Tarker's Mills", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 145, y: 500, summary: "The rural fictional community stalked across a calendar year in Cycle of the Werewolf.", workTitles: ["Cycle of the Werewolf"], source: wiki("Cycle_of_the_Werewolf") },
    { id: "harlow", name: "Harlow", kind: "fictional", region: "Maine", mapStatus: "approximate", x: 118, y: 505, summary: "The fictional Maine town associated with Jamie Morton's childhood in Revival.", workTitles: ["Revival"], source: wiki("Revival_(King_novel)") },
    { id: "bridgton", name: "Bridgton", kind: "real", region: "Maine", mapStatus: "exact", x: 98, y: 580, summary: "A real western Maine town closely associated with the setting and origins of The Mist.", workTitles: ["The Mist"], source: { name: "OpenStreetMap", url: "https://www.openstreetmap.org/search?query=Bridgton%2C%20Maine", note: "Real-place coordinate; literary relationship remains a separate editorial claim." } },
    { id: "bangor", name: "Bangor", kind: "real", region: "Maine", mapStatus: "inspired", x: 270, y: 430, summary: "A real Maine city whose geography and landmarks strongly inform King's fictional Derry.", workTitles: ["It", "Insomnia", "11/22/63"], inspiration: "Real-world reference for Derry", source: { name: "Bangor Daily News", url: "https://www.bangordailynews.com/2025/10/27/bangor/bangor-culture/why-stephen-king-chose-bangor-model-for-derry-horror-classic-it-joam40zk0w/", note: "Journalistic source documenting the Derry–Bangor relationship." } },
    { id: "durham", name: "Durham", kind: "real", region: "Maine", mapStatus: "inspired", x: 145, y: 595, summary: "King's childhood home town and one of the communities discussed in relation to Castle Rock's composite geography.", workTitles: ["The Body", "Needful Things"], inspiration: "A proposed component of Castle Rock", source: wiki("Castle_Rock_(Stephen_King)", "Secondary-source association, presented as influence rather than identity.") },
    { id: "portland", name: "Portland", kind: "real", region: "Maine", mapStatus: "exact", x: 135, y: 635, summary: "Maine's largest city and a recurring real-world reference point across King's New England geography.", workTitles: ["The Mist", "11/22/63"], source: { name: "OpenStreetMap", url: "https://www.openstreetmap.org/search?query=Portland%2C%20Maine", note: "Real-place coordinate; story links are editorial records." } },
    { id: "shawshank", name: "Shawshank State Prison", kind: "fictional", region: "Maine", mapStatus: "unmapped", summary: "The fictional Maine prison at the center of Rita Hayworth and Shawshank Redemption.", workTitles: ["Rita Hayworth and Shawshank Redemption"], source: wiki("Rita_Hayworth_and_Shawshank_Redemption", "Deliberately left off the map because no reliable coordinate is asserted.") },
    { id: "sidewinder", name: "Sidewinder", kind: "fictional", region: "Colorado", mapStatus: "unmapped", summary: "The fictional Colorado town nearest the Overlook Hotel.", workTitles: ["The Shining", "Doctor Sleep"], source: wiki("The_Shining_(novel)") },
    { id: "overlook-hotel", name: "The Overlook Hotel", kind: "fictional", region: "Colorado", mapStatus: "unmapped", summary: "The isolated fictional resort where the Torrance family spends the winter.", workTitles: ["The Shining", "Doctor Sleep"], inspiration: "The Stanley Hotel is among its documented inspirations", source: { name: "The Stanley Hotel", url: "https://www.stanleyhotel.com/about.html", note: "Source for inspiration, not a claim that the fictional and real hotels are identical." } },
    { id: "boulder", name: "Boulder", kind: "real", region: "Colorado", mapStatus: "unmapped", summary: "A real Colorado city that becomes a center of the Free Zone in The Stand.", workTitles: ["The Stand", "The Stand Uncut"], source: { name: "OpenStreetMap", url: "https://www.openstreetmap.org/search?query=Boulder%2C%20Colorado", note: "Real place; narrative role awaits edition-level citation." } },
    { id: "hemingford-home", name: "Hemingford Home", kind: "fictional", region: "Nebraska", mapStatus: "unmapped", summary: "Mother Abagail's fictional community and an early destination for survivors in The Stand.", workTitles: ["The Stand", "The Stand Uncut"], source: wiki("The_Stand") },
    { id: "desperation", name: "Desperation", kind: "fictional", region: "Nevada", mapStatus: "unmapped", summary: "A fictional mining town along U.S. Route 50 and the principal setting of Desperation.", workTitles: ["Desperation"], source: wiki("Desperation_(novel)") },
    { id: "duma-key", name: "Duma Key", kind: "fictional", region: "Florida", mapStatus: "unmapped", summary: "A fictional island off Florida's Gulf Coast where Edgar Freemantle's paintings acquire power.", workTitles: ["Duma Key"], source: wiki("Duma_Key") },
    { id: "mid-world", name: "Mid-World", kind: "fictional", region: "Other world", mapStatus: "unmapped", summary: "The world that contains Roland's long road toward the Dark Tower.", workTitles: ["The Dark Tower: The Gunslinger", "The Dark Tower II: The Drawing of the Three", "The Dark Tower III: The Waste Lands", "The Dark Tower IV: Wizard and Glass", "The Dark Tower V: Wolves of the Calla", "The Dark Tower VI: Song of Susannah", "The Dark Tower VII: The Dark Tower"], source: wiki("The_Dark_Tower_(series)") },
    { id: "gilead", name: "Gilead", kind: "fictional", region: "Mid-World", mapStatus: "unmapped", summary: "The fallen barony and home of Roland Deschain.", workTitles: ["The Dark Tower: The Gunslinger", "The Dark Tower IV: Wizard and Glass"], source: wiki("The_Dark_Tower_(series)") },
    { id: "calla-bryn-sturgis", name: "Calla Bryn Sturgis", kind: "fictional", region: "Mid-World", mapStatus: "unmapped", summary: "A farming community threatened by the Wolves and defended by Roland's ka-tet.", workTitles: ["The Dark Tower V: Wolves of the Calla", "Calla Bryn Sturgis"], source: wiki("Wolves_of_the_Calla") },
    { id: "cold-mountain", name: "Cold Mountain Penitentiary", kind: "fictional", region: "Louisiana", mapStatus: "unmapped", summary: "The fictional prison whose death-row block is known as the Green Mile.", workTitles: ["The Green Mile"], source: wiki("The_Green_Mile_(novel)") }
];
export const getPlace = (id: string) => places.find(p => p.id === id); export const placeWorks = (p: Place) => p.workTitles.map(t => works.find(w => w.title === t)).filter(Boolean); export const workPlaces = (title: string) => places.filter(p => p.workTitles.includes(title));
