"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Shuffle, X, Grid2X2, List, ArrowLeft, ArrowRight } from "lucide-react";
import { EvidenceGlyph } from "./icons";
import type { Book, Short, Villain, EntityRef } from "../../lib/types";
type Kind="book"|"story"|"villain"; type RecordItem=Book|Short|Villain;
const config={book:{title:"Books",kicker:"Published archive",intro:"Novels, collections and recovered records. Every publication becomes a doorway into the larger archive.",endpoint:"/api/books?limit=100",key:"books",search:"Search publications…"},story:{title:"Short stories",kicker:"Recovered manuscripts",intro:"Compact disturbances indexed as documents, fragments and incident reports rather than conventional cover art.",endpoint:"/api/shorts",key:"shorts",search:"Search recovered stories…"},villain:{title:"Villains",kicker:"Entity registry",intro:"Known threats catalogued through sightings, relationships and surviving evidence. No portrait can be trusted.",endpoint:"/api/villains",key:"villains",search:"Search entities and aliases…"}} as const;
function titleOf(item:RecordItem){return "title" in item?item.title:item.name}
function yearOf(item:RecordItem){return "year" in item?item.year:null}
function refs(item:RecordItem):EntityRef[]{if("villains" in item)return item.villains||[];return [...(item.books||[]),...(item.shorts||[])]}
export default function ArchiveExperience({kind}:{kind:Kind}){const c=config[kind];const [records,setRecords]=useState<RecordItem[]>([]);const [selected,setSelected]=useState<RecordItem|null>(null);const [query,setQuery]=useState("");const [sort,setSort]=useState("name");const [view,setView]=useState<"grid"|"list">("grid");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [page,setPage]=useState(1);const pageSize=12;
useEffect(()=>{setLoading(true);fetch(c.endpoint).then(async r=>{if(!r.ok)throw new Error(`Archive service returned ${r.status}`);return r.json()}).then(data=>setRecords(data[c.key]||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[c.endpoint,c.key]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const rows=records.filter(r=>!q||titleOf(r).toLowerCase().includes(q)||refs(r).some(x=>(x.name||x.title||"").toLowerCase().includes(q)));return rows.sort((a,b)=>sort==="year"?(yearOf(b)||0)-(yearOf(a)||0):titleOf(a).localeCompare(titleOf(b)))},[records,query,sort]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((page-1)*pageSize,page*pageSize);useEffect(()=>setPage(1),[query,sort]);
return <main className={`archivePage archive-${kind}`}><header className="archiveHero"><div className="heroGrid"/><div className="heroCopy"><span>{c.kicker}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="heroStats"><b>{records.length||"—"}</b><small>indexed records</small><i/></div></div><EvidenceGlyph kind={kind}/></header><section className="archiveToolbar"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/></label><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort records"><option value="name">Alphabetical</option><option value="year">Newest first</option></select><button onClick={()=>records.length&&setSelected(records[Math.floor(Math.random()*records.length)])}><Shuffle size={17}/><span>Random file</span></button><div className="viewSwitch"><button className={view==="grid"?"active":""} onClick={()=>setView("grid")} aria-label="Grid view"><Grid2X2 size={17}/></button><button className={view==="list"?"active":""} onClick={()=>setView("list")} aria-label="List view"><List size={18}/></button></div></section><div className="archiveMeta"><span>{error?"SERVICE INTERRUPTION":loading?"RECOVERING INDEX…":`${filtered.length} RECORDS LOCATED`}</span><span>PAGE {page} / {pages}</span></div>{error?<div className="archiveMessage"><b>Archive connection failed</b><p>{error}. Check your <code>.env.local</code> configuration and external API availability.</p></div>:loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><i key={i}/>)}</div>:<section className={`recordGrid ${view}`}>{visible.map((item,index)=><RecordCard key={`${kind}-${"id" in item?item.id:index}`} item={item} kind={kind} selected={selected===item} onSelect={()=>setSelected(item)}/>)}</section>}<footer className="pager"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ArrowLeft/> Previous</button><span>{Math.min((page-1)*pageSize+1,filtered.length)}–{Math.min(page*pageSize,filtered.length)} of {filtered.length}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next <ArrowRight/></button></footer>{selected&&<><button className="inspectorBackdrop" onClick={()=>setSelected(null)} aria-label="Close case file"/><Inspector item={selected} kind={kind} close={()=>setSelected(null)}/></>}</main>}
function RecordCard({item,kind,selected,onSelect}:{item:RecordItem;kind:Kind;selected:boolean;onSelect:()=>void}){const title=titleOf(item);const year=yearOf(item);const links=refs(item);const cover=kind==="book"?(item as Book).cover:null;return <button className={`recordCard ${selected?"selected":""}`} onClick={onSelect}><div className="artifact">{cover?<img src={cover} alt={`${title} cover`} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/>:<EvidenceGlyph kind={kind}/>}<span>{String(("id" in item&&item.id)||0).padStart(4,"0")}</span><i/></div><div className="recordCopy"><small>{kind==="book"?"PUBLICATION":kind==="story"?(item as Short).type||"MANUSCRIPT":"ENTITY FILE"}</small><h2>{title}</h2><p>{kind==="book"?(item as Book).publisher||"Publisher unrecorded":kind==="story"?(item as Short).collectedIn||(item as Short).originallyPublishedIn||"Collection unknown":`${(item as Villain).status||"UNKNOWN"} · ${(item as Villain).gender||"UNCLASSIFIED"}`}</p><footer><span>{year||"DATE UNKNOWN"}</span><span>{links.length} CONNECTIONS</span></footer></div></button>}
function Inspector({item,kind,close}:{item:RecordItem;kind:Kind;close:()=>void}){const title=titleOf(item);const links=refs(item);const cover=kind==="book"?(item as Book).cover:null;return <aside className="inspector" role="dialog" aria-modal="true" aria-label={`${title} case file`}><header><span>ARCHIVE CASE FILE</span><button onClick={close} aria-label="Close case file"><X/></button></header><div className="inspectorArtifact">{cover?<img src={cover} alt={`${title} cover`} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/>:<EvidenceGlyph kind={kind}/>}<b>{kind.toUpperCase()} / {String(("id" in item&&item.id)||0).padStart(4,"0")}</b></div><div className="inspectorBody"><small>{kind==="villain"?"KNOWN ENTITY":kind==="story"?"RECOVERED TEXT":"PUBLISHED WORK"}</small><h2>{title}</h2><dl>{kind==="book"&&<><div><dt>Published</dt><dd>{(item as Book).year||"Unknown"}</dd></div><div><dt>Publisher</dt><dd>{(item as Book).publisher||"Unrecorded"}</dd></div><div><dt>Pages</dt><dd>{(item as Book).pageCount||"Unknown"}</dd></div><div><dt>ISBN</dt><dd>{(item as Book).isbn||"Unrecorded"}</dd></div></>}{kind==="story"&&<><div><dt>Type</dt><dd>{(item as Short).type||"Unknown"}</dd></div><div><dt>Year</dt><dd>{(item as Short).year||"Unknown"}</dd></div><div><dt>First located in</dt><dd>{(item as Short).originallyPublishedIn||"Unrecorded"}</dd></div><div><dt>Collected in</dt><dd>{(item as Short).collectedIn||"Unrecorded"}</dd></div></>}{kind==="villain"&&<><div><dt>Status</dt><dd>{(item as Villain).status||"Unknown"}</dd></div><div><dt>Gender</dt><dd>{(item as Villain).gender||"Unknown"}</dd></div><div><dt>Classification</dt><dd>Type {(item as Villain).types_id||"?"}</dd></div></>}</dl>{kind==="book"&&<p className="summary">{(item as Book).description||"No verified summary survives in the archive."}</p>}<section><h3>Connections <span>{links.length}</span></h3>{links.length?<div className="connections">{links.slice(0,10).map((x,i)=><span key={i}>{x.name||x.title||"Unknown entity"}</span>)}</div>:<p className="muted">No confirmed relationships indexed.</p>}</section>{"notes" in item&&item.notes?.length>0&&<section><h3>Recovered notes</h3><ul>{item.notes.slice(0,5).map((n: string,i: number)=><li key={i}>{n}</li>)}</ul></section>}</div><footer>TRUTH STATUS · PARTIALLY VERIFIED</footer></aside>}
